spring:
  application:
    name: kua-fu
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kua_fu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    hikari:
      max-lifetime: 600000

    initialization-mode: always

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      cluster:
        refresh:
          adaptive: true
          period: 30000
      pool:
        max-wait: 10000
        max-idle: 10
        min-idle: 10
        max-active: 20

  data:
    redis:
      repositories:
        enabled: false

  boot:
    admin:
      client:
        enabled: false
        url: http://localhost:8999

server:
  address: 0.0.0.0
  port: 38000

service:
  id:
    node-id: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: com.mini.kuafu.service.**.domain
  mapper-locations: classpath*:com/mini/kuafu/service/**/dao/xml/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    com.mini.kuafu: DEBUG